// Code generated by the Encore v1.56.7 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-hista-api-dpc2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the hista-api-dpc2 Encore application.
 */
export default class Client {
    public readonly authentication: authentication.ServiceClient
    public readonly hista: hista.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.authentication = new authentication.ServiceClient(base)
        this.hista = new hista.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: authentication.AuthParams | AuthDataGenerator
}

export namespace authentication {
    export interface AuthParams {
        Token: string
    }

    export interface LoginParams {
        userName: string
        password: string
    }

    export interface LoginResponse {
        token: string
    }

    export interface UUIDResponse {
        id: string
    }

    export interface UserListResponse {
        users: UserResponse[]
    }

    export interface UserResponse {
        name: string
        id: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AddUserToProductInstance = this.AddUserToProductInstance.bind(this)
            this.GetPermissions = this.GetPermissions.bind(this)
            this.GetUsersForProductInstance = this.GetUsersForProductInstance.bind(this)
            this.Login = this.Login.bind(this)
            this.RemoveUserFromProductInstance = this.RemoveUserFromProductInstance.bind(this)
        }

        public async AddUserToProductInstance(productInstanceId: string, name: string): Promise<UUIDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(productInstanceId)}/users/${encodeURIComponent(name)}`)
            return await resp.json() as UUIDResponse
        }

        public async GetPermissions(): Promise<entity.AuthData> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/permissions`)
            return await resp.json() as entity.AuthData
        }

        public async GetUsersForProductInstance(productInstanceId: string): Promise<UserListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(productInstanceId)}/users`)
            return await resp.json() as UserListResponse
        }

        public async Login(params: LoginParams): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/login`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        public async RemoveUserFromProductInstance(productInstanceId: string, name: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(productInstanceId)}/users/${encodeURIComponent(name)}`)
        }
    }
}

export namespace hista {
    export interface ConditionEventListResponse {
        conditionEvents: ConditionEventMetaResponse[]
    }

    export interface ConditionEventMetaResponse {
        id: number
        date: string
    }

    export interface ConditionEventRequestParams {
        date: string
    }

    export interface ConditionEventResponse {
        id: number
        date: string
        conditions: ConditionResponse[]
    }

    export interface ConditionRequestParams {
        symptomName?: string | null
        symptomId?: number | null
        categoryId?: number | null
    }

    export interface ConditionResponse {
        id: number
        symptom: SymptomResponse
        severity: number
    }

    export interface DateParam {
        date: string
    }

    export interface DiaryResp {
        date: string
        type: string
        content: string
        severity: string
        category: string
    }

    export interface DiaryRespList {
        diaries: DiaryResp[]
    }

    export interface FoodParams {
        ingredientName?: string
        ingredientId?: number
    }

    export interface FoodResponse {
        id: number
        ingredientId: number
        foodCondition: string
        amount?: number
    }

    export interface FoodsResponse {
        foods: FoodResponse[]
    }

    export interface HeadacheListResponse {
        headaches: HeadacheResponse[]
    }

    export interface HeadacheResponse {
        id: number
        date: string
        severity: number
        types?: string[]
        positions?: string[]
        symptoms?: string[]
        description: string
    }

    export interface IDResponse {
        id: number
    }

    export interface IngredientListResponse {
        ingredients: IngredientResponse[]
    }

    export interface IngredientResponse {
        id: number
        name: string
        isArchived: boolean
        nutrition?: NutritionResponse
    }

    export interface IntakeListResponse {
        intakes: IntakeResponse[]
    }

    export interface IntakeResponse {
        date: string
        medicineId: number
        count: number
    }

    export interface MealListResponse {
        meals: MealMetaResponse[]
    }

    export interface MealMetaResponse {
        id: number
        date: string
    }

    export interface MealResponse {
        id: number
        date: string
        freshness: number
        stressLevel: number
        isAlone: boolean
        foods: FoodResponse[]
    }

    export interface MealStatisticsParams {
        id: number
        fromDate: string
        toDate: string
    }

    export interface MedicineListResponse {
        medicines: MedicineResponse[]
    }

    export interface MedicineResponse {
        id: number
        name: string
        isArchived: boolean
        sortOrder: number
    }

    export interface MoveMedicineParams {
        previousId?: number
        nextId?: number
    }

    export interface NoteListResponse {
        notes: NoteResponse[]
    }

    export interface NoteParams {
        date?: string | null
        text?: string | null
    }

    export interface NoteResponse {
        id: number
        date: string
        text: string
    }

    export interface NutritionResp {
        protein: number
        carbohydrate: number
        fat: number
        fiber: number
    }

    export interface NutritionResponse {
        protein: number
        carbohydrate: number
        fat: number
        fiber: number
    }

    export interface NutritionStatisticResponse {
        time: string
        nutrition: NutritionResp
    }

    export interface NutritionStatisticsParams {
        Interval: string
        From?: string | null
        To?: string | null
    }

    export interface NutritionStatisticsResponse {
        statistics: NutritionStatisticResponse[]
    }

    export interface PatchCategoryNameParams {
        name: string
    }

    export interface PatchFoodAmountParams {
        amount: number
    }

    export interface PatchFoodConditionParams {
        condition: string
    }

    export interface PatchHeadacheParams {
        date?: string | null
        description?: string | null
        severity?: number | null
        types?: headaches.HeadacheTypes | null
        symptoms?: headaches.HeadacheSymptoms | null
        positions?: headaches.HeadachePositions | null
    }

    export interface PatchIngredientParams {
        name?: string | null
        nutrition?: PatchNutritionParams | null
        archived?: boolean | null
    }

    export interface PatchMealParams {
        date?: string
        freshness?: number
        stressLevel?: number
        isAlone?: boolean
    }

    export interface PatchMedicineParams {
        name?: string
        archive?: boolean
    }

    export interface PatchNutritionParams {
        protein: number
        carbohydrate: number
        fat: number
        fiber: number
    }

    export interface PatchSeverityRequestParams {
        severity: number
    }

    export interface PatchStatusParams {
        date?: string | null
        morningFitness?: number | null
        morningSleep?: number | null
        eveningFitness?: number | null
    }

    export interface PatchSymptomCategoryParams {
        toCategoryId: number
    }

    export interface PatchSymptomNameParams {
        name: string
    }

    export interface PollenEventListResponse {
        pollens: PollenEventResponse[]
    }

    export interface PollenEventResponse {
        date: string
        pollens: PollenResponse[]
    }

    export interface PollenResponse {
        type: string
        intensity: number
        intensityString: string
    }

    export interface PostConditionResponse {
        condition: ConditionResponse
        symptoms?: SymptomCategoryListResponse | null
    }

    export interface PostFoodResponse {
        food: FoodResponse
        ingredients: IngredientListResponse
    }

    export interface PostHeadacheParams {
        date: string
        severity: number
    }

    export interface PostMealParams {
        date: string
    }

    export interface PostMedicineParams {
        name: string
    }

    export interface PostSymptomCategoryRequest {
        name: string
    }

    export interface StatisticBySymptom {
        symptomId: number
        severity: number
        hours72: number
        hours24: number
        hours1: number
    }

    export interface StatusListResponse {
        statuses: StatusResponse[]
    }

    export interface StatusResponse {
        id: number
        date: string
        morningFitness?: number | null
        eveningFitness?: number | null
        morningSleep?: number | null
    }

    export interface SymptomCategoryListResponse {
        Categories: SymptomCategoryResponse[]
    }

    export interface SymptomCategoryResponse {
        id: number
        name: string
        symptoms: SymptomResponse[]
    }

    export interface SymptomResponse {
        id: number
        name: string
        categoryId: number
    }

    export interface SymptomStatisticsResponse {
        count: number
        statistics: StatisticBySymptom[]
    }

    export interface TemplateItemParams {
        ingredientId: number
        condition: string
    }

    export interface TemplateItemResponse {
        item: number
        ingredientId: number
        condition: string
    }

    export interface TemplateListResponse {
        templates: TemplateResponse[]
    }

    export interface TemplateParams {
        name: string
        items: TemplateItemParams[]
    }

    export interface TemplateResponse {
        id: number
        name: string
        items: TemplateItemResponse[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ArchiveIngredient = this.ArchiveIngredient.bind(this)
            this.CreateConditionEvent = this.CreateConditionEvent.bind(this)
            this.CreateMedicine = this.CreateMedicine.bind(this)
            this.DecrementIntake = this.DecrementIntake.bind(this)
            this.DeleteCondition = this.DeleteCondition.bind(this)
            this.DeleteConditionEvent = this.DeleteConditionEvent.bind(this)
            this.DeleteFood = this.DeleteFood.bind(this)
            this.DeleteHeadache = this.DeleteHeadache.bind(this)
            this.DeleteMeal = this.DeleteMeal.bind(this)
            this.DeleteMedicine = this.DeleteMedicine.bind(this)
            this.DeleteNote = this.DeleteNote.bind(this)
            this.DeleteStatus = this.DeleteStatus.bind(this)
            this.DeleteSymptomCategory = this.DeleteSymptomCategory.bind(this)
            this.DeleteTemplate = this.DeleteTemplate.bind(this)
            this.GetConditionEvent = this.GetConditionEvent.bind(this)
            this.GetDiary = this.GetDiary.bind(this)
            this.GetFoods = this.GetFoods.bind(this)
            this.GetHeadache = this.GetHeadache.bind(this)
            this.GetMeal = this.GetMeal.bind(this)
            this.GetNutritionByInterval = this.GetNutritionByInterval.bind(this)
            this.GetStatisticsByIngredientId = this.GetStatisticsByIngredientId.bind(this)
            this.IncrementIntake = this.IncrementIntake.bind(this)
            this.ListConditionEvents = this.ListConditionEvents.bind(this)
            this.ListHeadaches = this.ListHeadaches.bind(this)
            this.ListIngredients = this.ListIngredients.bind(this)
            this.ListIntakes = this.ListIntakes.bind(this)
            this.ListMeals = this.ListMeals.bind(this)
            this.ListMedicines = this.ListMedicines.bind(this)
            this.ListNotes = this.ListNotes.bind(this)
            this.ListPollens = this.ListPollens.bind(this)
            this.ListStatus = this.ListStatus.bind(this)
            this.ListSymptoms = this.ListSymptoms.bind(this)
            this.ListTemplates = this.ListTemplates.bind(this)
            this.PatchCategoryName = this.PatchCategoryName.bind(this)
            this.PatchCondition = this.PatchCondition.bind(this)
            this.PatchDate = this.PatchDate.bind(this)
            this.PatchFoodAmount = this.PatchFoodAmount.bind(this)
            this.PatchFoodCondition = this.PatchFoodCondition.bind(this)
            this.PatchHeadache = this.PatchHeadache.bind(this)
            this.PatchIngredient = this.PatchIngredient.bind(this)
            this.PatchMeal = this.PatchMeal.bind(this)
            this.PatchMedicine = this.PatchMedicine.bind(this)
            this.PatchNote = this.PatchNote.bind(this)
            this.PatchStatus = this.PatchStatus.bind(this)
            this.PatchSymptomCategory = this.PatchSymptomCategory.bind(this)
            this.PatchSymptomName = this.PatchSymptomName.bind(this)
            this.PostCondition = this.PostCondition.bind(this)
            this.PostFood = this.PostFood.bind(this)
            this.PostFoodByTemplate = this.PostFoodByTemplate.bind(this)
            this.PostHeadache = this.PostHeadache.bind(this)
            this.PostMeal = this.PostMeal.bind(this)
            this.PostNote = this.PostNote.bind(this)
            this.PostStatus = this.PostStatus.bind(this)
            this.PostSymptomCategory = this.PostSymptomCategory.bind(this)
            this.PostTemplate = this.PostTemplate.bind(this)
            this.PutTemplate = this.PutTemplate.bind(this)
            this.ReorderMedicine = this.ReorderMedicine.bind(this)
        }

        /**
         * Deprecated: use normal PATCH endpoint with archived property
         */
        public async ArchiveIngredient(piid: string, id: number): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/ingredients/${encodeURIComponent(id)}/archive`)
        }

        public async CreateConditionEvent(piid: string): Promise<ConditionEventResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/condition-events`)
            return await resp.json() as ConditionEventResponse
        }

        public async CreateMedicine(piid: string, params: PostMedicineParams): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/medicines`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }

        public async DecrementIntake(piid: string, medicineId: number): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/intakes/medicines/${encodeURIComponent(medicineId)}/decrement`)
        }

        public async DeleteCondition(piid: string, conditionID: number): Promise<SymptomCategoryListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/conditions/${encodeURIComponent(conditionID)}`)
            return await resp.json() as SymptomCategoryListResponse
        }

        public async DeleteConditionEvent(piid: string, eventId: number): Promise<SymptomCategoryListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/condition-events/${encodeURIComponent(eventId)}`)
            return await resp.json() as SymptomCategoryListResponse
        }

        public async DeleteFood(piid: string, foodId: number): Promise<IngredientListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/foods/${encodeURIComponent(foodId)}`)
            return await resp.json() as IngredientListResponse
        }

        public async DeleteHeadache(piid: string, id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/headaches/${encodeURIComponent(id)}`)
        }

        public async DeleteMeal(piid: string, id: number): Promise<IngredientListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/meals/${encodeURIComponent(id)}`)
            return await resp.json() as IngredientListResponse
        }

        public async DeleteMedicine(piid: string, medicineId: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/medicines/${encodeURIComponent(medicineId)}`)
        }

        public async DeleteNote(piid: string, noteId: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/notes/${encodeURIComponent(noteId)}`)
        }

        public async DeleteStatus(piid: string, id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/status/${encodeURIComponent(id)}`)
        }

        public async DeleteSymptomCategory(piid: string, id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/symptom-categories/${encodeURIComponent(id)}`)
        }

        public async DeleteTemplate(piid: string, id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/piid/${encodeURIComponent(piid)}/templates/${encodeURIComponent(id)}`)
        }

        public async GetConditionEvent(piid: string, eventId: number): Promise<ConditionEventResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/condition-events/${encodeURIComponent(eventId)}`)
            return await resp.json() as ConditionEventResponse
        }

        public async GetDiary(piid: string): Promise<DiaryRespList> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/diary`)
            return await resp.json() as DiaryRespList
        }

        public async GetFoods(piid: string, mealId: number): Promise<FoodsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/meal/${encodeURIComponent(mealId)}/foods`)
            return await resp.json() as FoodsResponse
        }

        public async GetHeadache(piid: string, id: number): Promise<HeadacheResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/headaches/${encodeURIComponent(id)}`)
            return await resp.json() as HeadacheResponse
        }

        public async GetMeal(piid: string, id: number): Promise<MealResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/meals/${encodeURIComponent(id)}`)
            return await resp.json() as MealResponse
        }

        public async GetNutritionByInterval(piid: string, params: NutritionStatisticsParams): Promise<NutritionStatisticsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                from:     params.From === undefined ? undefined : String(params.From),
                interval: params.Interval,
                to:       params.To === undefined ? undefined : String(params.To),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/statistics/nutrition`, undefined, {query})
            return await resp.json() as NutritionStatisticsResponse
        }

        public async GetStatisticsByIngredientId(piid: string, params: MealStatisticsParams): Promise<SymptomStatisticsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "from_date": String(params.fromDate),
                id:          String(params.id),
                "to_date":   String(params.toDate),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/statistics/ingredients`, undefined, {query})
            return await resp.json() as SymptomStatisticsResponse
        }

        public async IncrementIntake(piid: string, medicineId: number): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/intakes/medicines/${encodeURIComponent(medicineId)}/increment`)
        }

        public async ListConditionEvents(piid: string): Promise<ConditionEventListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/condition-events`)
            return await resp.json() as ConditionEventListResponse
        }

        public async ListHeadaches(piid: string): Promise<HeadacheListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/headaches`)
            return await resp.json() as HeadacheListResponse
        }

        public async ListIngredients(piid: string): Promise<IngredientListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/ingredients`)
            return await resp.json() as IngredientListResponse
        }

        public async ListIntakes(piid: string): Promise<IntakeListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/intakes`)
            return await resp.json() as IntakeListResponse
        }

        public async ListMeals(piid: string): Promise<MealListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/meals`)
            return await resp.json() as MealListResponse
        }

        public async ListMedicines(piid: string): Promise<MedicineListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/medicines`)
            return await resp.json() as MedicineListResponse
        }

        public async ListNotes(piid: string): Promise<NoteListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/notes`)
            return await resp.json() as NoteListResponse
        }

        public async ListPollens(piid: string): Promise<PollenEventListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/pollen`)
            return await resp.json() as PollenEventListResponse
        }

        public async ListStatus(piid: string): Promise<StatusListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/status`)
            return await resp.json() as StatusListResponse
        }

        public async ListSymptoms(piid: string): Promise<SymptomCategoryListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/symptoms`)
            return await resp.json() as SymptomCategoryListResponse
        }

        public async ListTemplates(piid: string): Promise<TemplateListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/piid/${encodeURIComponent(piid)}/templates`)
            return await resp.json() as TemplateListResponse
        }

        public async PatchCategoryName(piid: string, id: number, params: PatchCategoryNameParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/symptom-categories/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async PatchCondition(piid: string, conditionID: number, params: PatchSeverityRequestParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/conditions/${encodeURIComponent(conditionID)}`, JSON.stringify(params))
        }

        public async PatchDate(piid: string, eventId: number, params: ConditionEventRequestParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/condition-events/${encodeURIComponent(eventId)}`, JSON.stringify(params))
        }

        public async PatchFoodAmount(piid: string, foodId: number, params: PatchFoodAmountParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/foods/${encodeURIComponent(foodId)}/amount`, JSON.stringify(params))
        }

        public async PatchFoodCondition(piid: string, foodId: number, params: PatchFoodConditionParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/foods/${encodeURIComponent(foodId)}/condition`, JSON.stringify(params))
        }

        public async PatchHeadache(piid: string, id: number, params: PatchHeadacheParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/headaches/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async PatchIngredient(piid: string, id: number, params: PatchIngredientParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/ingredients/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async PatchMeal(piid: string, id: number, params: PatchMealParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/meals/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async PatchMedicine(piid: string, medicineId: number, params: PatchMedicineParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/medicines/${encodeURIComponent(medicineId)}`, JSON.stringify(params))
        }

        public async PatchNote(piid: string, noteId: number, params: NoteParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/notes/${encodeURIComponent(noteId)}`, JSON.stringify(params))
        }

        public async PatchStatus(piid: string, id: number, params: PatchStatusParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/status/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async PatchSymptomCategory(piid: string, id: number, params: PatchSymptomCategoryParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/symptoms/${encodeURIComponent(id)}/category`, JSON.stringify(params))
        }

        public async PatchSymptomName(piid: string, id: number, params: PatchSymptomNameParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/symptoms/${encodeURIComponent(id)}/name`, JSON.stringify(params))
        }

        public async PostCondition(piid: string, eventId: number, params: ConditionRequestParams): Promise<PostConditionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/condition-events/${encodeURIComponent(eventId)}/conditions`, JSON.stringify(params))
            return await resp.json() as PostConditionResponse
        }

        public async PostFood(piid: string, mealId: number, params: FoodParams): Promise<PostFoodResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/meal/${encodeURIComponent(mealId)}/foods`, JSON.stringify(params))
            return await resp.json() as PostFoodResponse
        }

        public async PostFoodByTemplate(piid: string, mealId: number, templateId: number): Promise<FoodsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/meal/${encodeURIComponent(mealId)}/foods/by-template/${encodeURIComponent(templateId)}`)
            return await resp.json() as FoodsResponse
        }

        public async PostHeadache(piid: string, params: PostHeadacheParams): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/headaches`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }

        public async PostMeal(piid: string, params: PostMealParams): Promise<MealResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/meals`, JSON.stringify(params))
            return await resp.json() as MealResponse
        }

        public async PostNote(piid: string): Promise<NoteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/notes`)
            return await resp.json() as NoteResponse
        }

        public async PostStatus(piid: string, params: DateParam): Promise<StatusResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/status`, JSON.stringify(params))
            return await resp.json() as StatusResponse
        }

        public async PostSymptomCategory(piid: string, params: PostSymptomCategoryRequest): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/symptom-categories`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }

        public async PostTemplate(piid: string, params: TemplateParams): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/piid/${encodeURIComponent(piid)}/templates`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }

        public async PutTemplate(piid: string, id: number, params: TemplateParams): Promise<void> {
            await this.baseClient.callTypedAPI("PUT", `/piid/${encodeURIComponent(piid)}/templates/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async ReorderMedicine(piid: string, medicineId: number, params: MoveMedicineParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/piid/${encodeURIComponent(piid)}/medicines/${encodeURIComponent(medicineId)}/reorder`, JSON.stringify(params))
        }
    }
}

export namespace entity {
    export interface AuthData {
        instances: AuthProductInstance[]
        userName: string
        userId: string
    }

    export interface AuthProductInstance {
        appMapping: { [key: string]: boolean }
        piid: string
        product: string
    }
}

export namespace headaches {
    export type HeadachePosition = string

    export type HeadachePositions = HeadachePosition[]

    export type HeadacheSymptom = string

    export type HeadacheSymptoms = HeadacheSymptom[]

    export type HeadacheType = string

    export type HeadacheTypes = HeadacheType[]
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | authentication.AuthParams
  | Promise<authentication.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "hista-api-dpc2-Generated-TS-Client (Encore/v1.56.7)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: authentication.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.Token,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
