// Code generated by the Encore v1.35.3 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-hista-api-dpc2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

/**
 * Client is an API client for the hista-api-dpc2 Encore application. 
 */
export default class Client {
    public readonly internalAuth: internalAuth.ServiceClient
    public readonly meals: meals.ServiceClient
    public readonly notes: notes.ServiceClient
    public readonly statistics: statistics.ServiceClient
    public readonly symptoms: symptoms.ServiceClient


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        const base = new BaseClient(target, options ?? {})
        this.internalAuth = new internalAuth.ServiceClient(base)
        this.meals = new meals.ServiceClient(base)
        this.notes = new notes.ServiceClient(base)
        this.statistics = new statistics.ServiceClient(base)
        this.symptoms = new symptoms.ServiceClient(base)
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: internalAuth.AuthParams | AuthDataGenerator
}

export namespace internalAuth {
    export interface AuthParams {
        Authorization: string
        UserName: string
    }

    export interface LoginParams {
        userName: string
        password: string
    }

    export interface LoginResponse {
        token: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        public async Login(params: LoginParams): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/login`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }
    }
}

export namespace meals {
    export type FoodCondition = string

    export interface FoodConditionParams {
        Condition: string
    }

    export interface FoodParams {
        ingredientName: string
        condition: FoodCondition
    }

    export interface FoodResponse {
        id: number
        ingredient: IngredientResponse
        foodCondition: FoodCondition
    }

    export interface FoodsResponse {
        foods: FoodResponse[]
    }

    export interface IDResponse {
        id: number
    }

    export interface IngredientResponse {
        id: number
        name: string
    }

    export interface IngredientsResponse {
        ingredients: IngredientResponse[]
    }

    export interface MealMetaResponse {
        id: number
        date: string
    }

    export interface MealParams {
        date: string
    }

    export interface MealResponse {
        id: number
        date: string
        foods: FoodResponse[]
    }

    export interface MealsResponse {
        meals: MealMetaResponse[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        public async DeleteFood(mealId: number, foodId: number): Promise<void> {
            await this.baseClient.callAPI("DELETE", `/meal/${encodeURIComponent(mealId)}/foods/${encodeURIComponent(foodId)}`)
        }

        public async DeleteMeal(id: number): Promise<void> {
            await this.baseClient.callAPI("DELETE", `/meals/${encodeURIComponent(id)}`)
        }

        public async GetFoods(mealId: number): Promise<FoodsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/meal/${encodeURIComponent(mealId)}/foods`)
            return await resp.json() as FoodsResponse
        }

        public async GetIngredients(): Promise<IngredientsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/ingredient`)
            return await resp.json() as IngredientsResponse
        }

        public async GetMeal(id: number): Promise<MealResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/meals/${encodeURIComponent(id)}`)
            return await resp.json() as MealResponse
        }

        public async GetMeals(): Promise<MealsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/meals`)
            return await resp.json() as MealsResponse
        }

        public async PatchFoodCondition(mealId: number, foodId: number, params: FoodConditionParams): Promise<void> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                condition: params.Condition,
            })

            await this.baseClient.callAPI("PATCH", `/meal/${encodeURIComponent(mealId)}/foods/${encodeURIComponent(foodId)}/condition`, undefined, {query})
        }

        public async PatchMealTime(id: number, params: MealParams): Promise<void> {
            await this.baseClient.callAPI("PATCH", `/meals/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        public async PostFood(mealId: number, params: FoodParams): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/meal/${encodeURIComponent(mealId)}/foods`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }

        public async PostMeal(params: MealParams): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/meals`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }
    }
}

export namespace notes {
    export interface NoteParams {
        date?: string
        text?: string
    }

    export interface NoteResp {
        id: number
        date: string
        text: string
    }

    export interface NotesResp {
        notes: NoteResp[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        public async DeleteNote(noteId: number): Promise<void> {
            await this.baseClient.callAPI("DELETE", `/notes/${encodeURIComponent(noteId)}`)
        }

        public async GetNotes(): Promise<NotesResp> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/notes`)
            return await resp.json() as NotesResp
        }

        public async PatchNote(noteId: number, params: NoteParams): Promise<NoteResp> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("PATCH", `/notes/${encodeURIComponent(noteId)}`, JSON.stringify(params))
            return await resp.json() as NoteResp
        }

        public async PostNote(): Promise<NoteResp> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/notes`)
            return await resp.json() as NoteResp
        }
    }
}

export namespace statistics {
    export interface DiaryResp {
        diaries: RawDiary[]
    }

    export type DiaryType = string

    export interface RawDiary {
        date: string
        hour: number
        type: DiaryType
        content: string
        severity: string
        category: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        public async GetDiary(): Promise<DiaryResp> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/diary`)
            return await resp.json() as DiaryResp
        }
    }
}

export namespace symptoms {
    export interface ConditionEventMetaResponse {
        id: number
        date: string
    }

    export interface ConditionEventRequestParams {
        date: string
    }

    export interface ConditionEventResponse {
        id: number
        date: string
        conditions: ConditionResponse[]
    }

    export interface ConditionEventsResponse {
        conditionEvents: ConditionEventMetaResponse[]
    }

    export interface ConditionRequestParams {
        symptomName: string
        categoryId: number
    }

    export interface ConditionResponse {
        id: number
        symptom: SymptomResponse
        severity: ConditionSeverity
    }

    export type ConditionSeverity = number

    export interface IDResponse {
        id: number
    }

    export interface PatchSeverityRequestParams {
        severity: ConditionSeverity
    }

    export interface PostConditionResponse {
        condition: ConditionResponse
        symptoms: SymptomCategoriesResponse
    }

    export interface PostSymptomCategoryRequest {
        name: string
    }

    export interface SymptomCategoriesResponse {
        Categories: SymptomCategoryResponse[]
    }

    export interface SymptomCategoryResponse {
        id: number
        name: string
        symptoms: SymptomResponse[]
    }

    export interface SymptomResponse {
        id: number
        name: string
        categoryId: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        public async CreateConditionEvent(params: ConditionEventRequestParams): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/condition-events`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }

        public async DeleteCondition(conditionID: number): Promise<SymptomCategoriesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("DELETE", `/conditions/${encodeURIComponent(conditionID)}`)
            return await resp.json() as SymptomCategoriesResponse
        }

        public async DeleteConditionEvent(eventId: number): Promise<void> {
            await this.baseClient.callAPI("DELETE", `/condition-events/${encodeURIComponent(eventId)}`)
        }

        public async GetConditionEvent(eventId: number): Promise<ConditionEventResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/condition-events/${encodeURIComponent(eventId)}`)
            return await resp.json() as ConditionEventResponse
        }

        public async GetConditionEvents(): Promise<ConditionEventsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/condition-events`)
            return await resp.json() as ConditionEventsResponse
        }

        public async GetSymptoms(): Promise<SymptomCategoriesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("GET", `/symptoms`)
            return await resp.json() as SymptomCategoriesResponse
        }

        public async PatchCondition(conditionID: number, params: PatchSeverityRequestParams): Promise<void> {
            await this.baseClient.callAPI("PATCH", `/conditions/${encodeURIComponent(conditionID)}`, JSON.stringify(params))
        }

        public async PatchDate(eventId: number, params: ConditionEventRequestParams): Promise<void> {
            await this.baseClient.callAPI("PATCH", `/condition-events/${encodeURIComponent(eventId)}`, JSON.stringify(params))
        }

        public async PostCondition(eventId: number, params: ConditionRequestParams): Promise<PostConditionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/condition-events/${encodeURIComponent(eventId)}/conditions`, JSON.stringify(params))
            return await resp.json() as PostConditionResponse
        }

        public async PostConditionBySymptomID(eventId: number, symptomId: number): Promise<ConditionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/condition-events/${encodeURIComponent(eventId)}/conditions/symptoms/${encodeURIComponent(symptomId)}`)
            return await resp.json() as ConditionResponse
        }

        public async PostSymptomCategory(params: PostSymptomCategoryRequest): Promise<IDResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callAPI("POST", `/symptoms/categories`, JSON.stringify(params))
            return await resp.json() as IDResponse
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | internalAuth.AuthParams
  | Promise<internalAuth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {
            "Content-Type": "application/json",
        }

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (typeof window === "undefined") {
            this.headers["User-Agent"] = "hista-api-dpc2-Generated-TS-Client (Encore/v1.35.3)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }

    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: BodyInit, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // If authorization data generator is present, call it and add the returned data to the request
        let authData: internalAuth.AuthParams | undefined
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator()
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise
            } else {
                authData = mayBePromise
            }
        }

        // If we now have authentication data, add it to the request
        if (authData) {
            init.headers["authorization"] = authData.Authorization
            init.headers["username"] = authData.UserName
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null && 
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);
        
        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })
        
        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) { 
            (this as any).__proto__ = APIError.prototype 
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }
        
        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
