name: Test

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-24.04
    permissions: 
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
            cache: true

      - name: Get packages
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Knip
        run: pnpm knip

      - name: Typescript
        run: pnpm typecheck

      - name: Dependencies
        run: pnpm dependencies:ci

      - name: Test
        run: pnpm test:nowatch
        env:
          CI: true
          TZ: Europe/Berlin

      - name: 'notify vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
            name: Vercel - hista-ui Test
